# Generated by Django 4.1.7 on 2023-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="code", field=models.CharField(max_length=6),
        ),
    ]
